### ISSUE TITLE
defineProps in 2.1.0 converts incoming prop value of empty string to boolean "true"

### ISSUE THREAD

**Issue by richardtallent-erm** [sxzz/unplugin-vue-macros#351] opened 2023-04-28 22:52 UTC
### Describe the bug

Ok, this is a weird one!

- Everything works fine in 2.0.0.
- Everything works fine **under Vite HMR** in 2.1.0 (`npm run dev`).
- Bug happens only the **built** version of the site (locally and on my server).

I have a common prop interface for my field components, which looks something like this (I've simplified it a bit).

```ts
type IFieldValue = string | string[] | number | Date | boolean

interface IFormField {
  fieldType: string
  label: string
  isRequired: boolean
}

interface IFieldProps {
  field: IFormField
  modelValue: IFieldValue
}
```

Then, each of my field components (rich wrappers for text, number, date, checkbox, textarea, etc. HTML field elements, each of which is designed to deal with a subset of `IFieldValue` values) uses this interface for its props:

```ts
import type { IFieldProps } from "./FieldProps"
const props = defineProps<IFieldProps>()
```

These components don't use `withDefaults`.

The problem is, if a component is sent a `modelValue` of `""` (empty string), the value the component receives is actually a boolean `true`. Other values seem to pass through properly, I've only noticed an issue with empty strings.

Some properties of `field` above also get converted to `true`, but I **know** `modelValue` does, since that value becomes the visible value of the text field.

Rolling back to 2.0.0 resolved the issue.

I can try to come up with a minimal reproduction, if needed.

### Reproduction

https://github.com/richardtallent

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 14.42 GB / 31.73 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2023-04-29 15:42
I tried your code, but cannot reproduce it. Could you please provide a reproduction repo plz?

**Comment by richardtallent-erm** [comment] 2023-05-01 12:47
Sure, will try to do so today.

**Comment by richardtallent-erm** [comment] 2023-05-01 16:03
Minimal reproduction repo here:

https://github.com/richardtallent/unplugin-issue-351

Steps to reproduce:

```
npm run build
npx static dist
```

The issue starts with version 2.1.0 and is still there in 2.1.1.

It occurs regardless of:

- The order of `string` and `boolean` in the union type
- Whether the union type is directly in the `defineProps<{...}>`, indirectly in it via a separate `type` declaration, or a type imported from another file.
- Whether the `modelValue` is set with a static attribute value or v-bound to a blank string value.

**Comment by sxzz** [comment] 2023-05-01 19:28
Thanks for your reproduction. It has been fixed and will be released soon!

**Closed** 2023-05-01 19:28 UTC
Labels: bug
