### ISSUE TITLE
unplugin-vue-define-options TypeError

### ISSUE THREAD

**Issue by amirtbi** [sxzz/unplugin-vue-macros#203] opened 2023-01-07 08:54 UTC
I am using the unplugin-vue-define-options in Vue.js 3+  Vite + typescript. When I run my app, the following error appears. 

` [vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')
`
How can solve this issue?

**Comment by sxzz** [comment] 2023-01-07 08:57
Could you please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)?

https://antfu.me/posts/why-reproductions-are-required

**Comment by ecountergg** [comment] 2023-01-08 03:15
> I am using the unplugin-vue-define-options in Vue.js 3+ Vite + typescript. When I run my app, the following error appears.
> 
> `[vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')` How can solve this issue?

I had the same problem too, did you resolve it?

**Comment by amirtbi** [comment] 2023-01-08 05:22
> Could you please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> https://antfu.me/posts/why-reproductions-are-required

Yes, ofcourse

**Comment by fernandozhaxi** [comment] 2023-01-09 02:08
> > I am using the unplugin-vue-define-options in Vue.js 3+ Vite + typescript. When I run my app, the following error appears.
> > `[vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')` How can solve this issue?
> 
> I had the same problem too, did you resolve it?

Probably caused by version upgraded，I fixed the version at 0.12.2, and it's ok

**Comment by sxzz** [comment] 2023-01-16 08:00
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed** 2023-01-16 07:59 UTC

**Comment by Erutan409** [comment] 2023-03-26 14:02
> > > I am using the unplugin-vue-define-options in Vue.js 3+ Vite + typescript. When I run my app, the following error appears.
> > > `[vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')` How can solve this issue?
> > 
> > 
> > I had the same problem too, did you resolve it?
> 
> Probably caused by version upgraded，I fixed the version at 0.12.2, and it's ok

I don't see how this is a resolution...
