### ISSUE TITLE
Cannot find module 'unplugin-vue-macros/vite' or its corresponding type declarations. Translation: This could be one of two things - either unplugin-vue-macros/vite doesn't exist on your file system, or I can't find any type declarations for it.

### ISSUE THREAD

**Issue by g1ronn1mo** [sxzz/unplugin-vue-macros#297] opened 2023-03-07 08:38 UTC
### Describe the bug

I use Vue3 with vite. 

When I try to install it, with

`npm i -D unplugin-vue-macros`

 the folder: "unplugin-vue-macros/vite" did not get created and I get an error: "Cannot find module 'unplugin-vue-macros/vite' or its corresponding type declarations."

![image](https://user-images.githubusercontent.com/85943218/223368064-c479445e-d39a-43ec-a2eb-336d2fc37e83.png)

### Reproduction

Don't have

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13400F
    Memory: 7.19 GB / 15.84 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE    
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: Spartan (44.22621.1344.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2023-03-07 09:02
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed** 2023-03-07 09:59 UTC

**Comment by pany-ang** [comment] 2023-04-11 09:04
1. 如果 ts 版本小于 5，那么出现这个告警的原因应该是最新版 vscode，测试后发现好像 vscode 1.74 以及更早的版本不会出现该告警（这种情况下，你几乎只能忍着这个警告不管，其他措施会导致 build 报错，或者降低你的 vscode 版本）

2. 如果 ts 版本大于 5，那么你可以选择将 moduleResolution 配置为 bundler，但是这样的话，其他依赖（比如 Element Plus）可能就会疯狂报错（等待官方修复这个问题中...）。你也可以选择“// @ts-expect-error”来忽略这个错误，忽略后能正常 build

3. ts 小于 5，并且又是最新版 vscode 时最难受，几乎处理不了这个报错

所以总结一下，如果 ts 小于 5，那么就不要去管它，issues 里面的别人给的方法，几乎都会导致 build 出错。如果 ts 大于 5，那么就暂时用“// @ts-expect-error”来忽略这个错误，这样能正常 build

1. If the TS version is less than 5, then the reason for this alarm should be the latest version of VSCODE, after testing, it seems that VSCODE 1.74 and earlier versions will not appear this alarm (in this case, you can almost only endure this warning, other measures will cause build errors, or reduce your VSCODE version)

2. If the ts version is greater than 5, then you can choose to configure moduleResolution as a bundler, but in this case, other dependencies (such as Element Plus) may report crazy errors (waiting for the official fix of this problem...). ）。 You can also select "// @ts-expect-error" to ignore this error, and it will build normally after ignoring it

3. TS is less than 5, and it is the most uncomfortable when the latest version of VSCODE, and it is almost impossible to handle this error

So to sum up, if ts is less than 5, then don't care about it, the methods given by others in issues will almost always cause build errors. If ts is greater than 5, then temporarily ignore this error with "// @ts-expect-error", so that it can build normally
