### ISSUE TITLE
vue-cli5 中引入unplugin-vue-define-options 开发环境报 defineOptions is not defined

### ISSUE THREAD

**Issue by HuangFeiPeng** [sxzz/unplugin-vue-macros#319] opened 2023-03-23 09:55 UTC
### Describe the bug

vue-cli5+vue3+ts基础环境，在项目中引入unplugin-vue-define-options 库 按照文档配置执行yarn run dev 启动进入页面报 defineOptions is not defined。
相关配置如下，望您指导迷津。
package.json 如下：
```json 
 "devDependencies": {
        "@types/lodash": "^4.14.191",
        "@types/nprogress": "^0.2.0",
        "@typescript-eslint/eslint-plugin": "^5.4.0",
        "@typescript-eslint/parser": "^5.4.0",
        "@vue-macros/volar": "^0.9.2",
        "@vue/cli-plugin-babel": "~5.0.0",
        "@vue/cli-plugin-eslint": "~5.0.0",
        "@vue/cli-plugin-router": "~5.0.0",
        "@vue/cli-plugin-typescript": "~5.0.0",
        "@vue/cli-service": "~5.0.0",
        "@vue/eslint-config-typescript": "^9.1.0",
        "eslint": "^7.32.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-vue": "^8.0.3",
        "prettier": "^2.8.1",
        "sass": "^1.32.7",
        "sass-loader": "^12.0.0",
        "typescript": "~4.5.5",
        "unplugin-vue-define-options": "^1.3.1"
    }
````
typescript.json
```json 
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "useDefineForClassFields": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "unplugin-vue-define-options/macros-global"
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

````
vue.config.js
```js 
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
    transpileDependencies: true,
    devServer: {
        https: false,
    },
    configureWebpack: {
        plugins: [require('unplugin-vue-define-options/webpack')()],
    },
    parallel: false,
})

````

```vue 
<script setup lang="ts">
defineOptions({
    name: 'Home'
})
</script>

````

### Reproduction

none

### System Info

```Shell
index.vue?b0e9:20 Uncaught (in promise) ReferenceError: defineOptions is not defined
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HuangFeiPeng** [comment] 2023-03-23 09:56
is 提的可能不够规范敬请谅解，如果还缺少哪些信息我愿意配合提供。

**Comment by sxzz** [comment] 2023-03-23 10:42
请提供一个完整的可复现仓库

**Comment by sxzz** [comment] 2023-03-23 17:06
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

---

See also #23

**Closed by sxzz** 2023-03-23 17:06 UTC

**Comment by thatsgolden** [comment] 2024-06-17 03:57
怎么解决的？Vue2.7 我也遇到了

**Comment by sxzz** [comment] 2024-06-17 04:01
请打开一个新 issue 并提供一个最小复现仓库。
https://antfu.me/posts/why-reproductions-are-required-zh
