### ISSUE TITLE
Cannot load props in component in other packages.

### ISSUE THREAD

**Issue by keymasroy** [sxzz/unplugin-vue-macros#300] opened 2023-03-10 06:03 UTC
### Describe the bug

I made component as below.
```typescript
// u-code-combobox.vue
import type { CodeComboBoxProps, CodeItem } from './composables/code-combo'

export interface UCodeComboBoxProps extends CodeComboBoxProps {
  /**
   * model value
   */
  modelValue?: string
}

const props = withDefaults(defineProps<UCodeComboBoxProps>(), {
})
```

```typescript
// './composables/code-combo'

export interface CodeComboBoxProps extends Record<string, any> {
  grpCd: string
}
```

It works fine in my project.
And then publish my package in my private nexus.
But props has only modelValue and lost grpCd value.

Maybe ignore scope in node_modules.

Is it correct and any solution to work component in node_modules package?

### Reproduction

Nothing

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   
    Memory: 12.24 GB / 31.76 GB
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2023-03-10 06:55
Vue Macros will resolve the type from node_modules.

Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Comment by sxzz** [comment] 2023-03-16 16:35
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed by sxzz** 2023-03-16 16:35 UTC
