### ISSUE TITLE
Cannot find module 'unplugin-vue-macros/vite' or its corresponding type declarations VScode

### ISSUE THREAD

**Issue by rvfakie** [sxzz/unplugin-vue-macros#338] opened 2023-04-13 22:52 UTC
### Describe the bug

After installing dependency `unplugin-vue-macros` and importing in `vite.config.ts` as [docs](https://vue-macros.sxzz.moe/macros/setup-sfc.html) says 

```
import VueMacros from 'unplugin-vue-macros/vite';
```

I've got TS error in VSCode:
```
Cannot find module 'unplugin-vue-macros/vite' or its corresponding type declarations.ts(2307)
```

But plugin still works.

<img width="897" alt="Screenshot 2023-04-14 at 02 46 08" src="https://user-images.githubusercontent.com/19621913/231899870-4fc365d5-bba4-40a4-8ade-3ad5b501921f.png">

### Reproduction

`npm i -D unplugin-vue-macros` and see bug description

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 177.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2023-04-13 23:25
Duplicate of #257

**Closed by sxzz** 2023-04-13 23:25 UTC
