### ISSUE TITLE
升级vue后， vite.config.js中 transformShortVmodel 报错

### ISSUE THREAD

**Issue by selegiline** [sxzz/unplugin-vue-macros#152] opened 2022-11-16 15:33 UTC
### Clear and concise description of the problem

Type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.41/node_modules/@vue/compiler-core/dist/compiler-core").NodeTransform' is not assignable to type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.45/node_modules/@vue/compiler-core/dist/compiler-core").NodeTransform'.
  Types of parameters 'node' and 'node' are incompatible.
    Type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.45/node_modules/@vue/compiler-core/dist/compiler-core").RootNode | import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.45/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode' is not assignable to type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.41/node_modules/@vue/compiler-core/dist/compiler-core").RootNode | import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.41/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode'.
      Type 'RootNode' is not assignable to type 'RootNode | TemplateChildNode'.
        Type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.45/node_modules/@vue/compiler-core/dist/compiler-core").RootNode' is not assignable to type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.41/node_modules/@vue/compiler-core/dist/compiler-core").RootNode'.
          Types of property 'type' are incompatible.
            Type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.45/node_modules/@vue/compiler-core/dist/compiler-core").NodeTypes.ROOT' is not assignable to type 'import("C:/Users/kodaku/Desktop/vue-hq/node_modules/.pnpm/@vue+compiler-core@3.2.41/node_modules/@vue/compiler-core/dist/compiler-core").NodeTypes.ROOT'

### Suggested solution

升级一下

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment] 2022-11-16 18:24
Please provide a reproduction repo.

**Comment by sxzz** [comment] 2022-11-20 04:58
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Comment by sxzz** [comment] 2022-12-15 15:39
@david50407 感谢反馈，调查中

**Closed** 2022-12-27 13:22 UTC
Labels: needs reproduction
